name: redaa
recipe: drupal10
config:
  php: '8.2'
  webroot: docroot
  xdebug: debug
  composer: []
  composer_version: '2'
services:
  appserver:
    # Install Imagick PECL extension which isn't included with PHP 8.3
    # https://docs.lando.dev/plugins/php/extensions.html#installed-extensions
    build_as_root:
      - apt update && apt install libgmp-dev -y && docker-php-ext-install gmp
      - /app/scripts/imagick.sh
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/docroot'
        DRUSH_OPTIONS_URI: 'https://redaa.lndo.site'
        XDEBUG_MODE: 'debug,develop'
  database:
    type: mariadb:10.11
    creds:
      user: database
      password: database
      database: database
  node:
    type: node:16
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
proxy:
  mailhog:
    - mail.redaa.lndo.site
tooling:
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node
  fix-imagick:
    service: appserver
    description: Update Imagick policy for PDF
    cmd: sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
    user: root
  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo
  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
