name: redaa
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: eeab35dc-2307-455c-b232-5f436ecb0af8
  ah_site_group: gwi
  php: '8.1'
services:
  appserver:
    webroot: docroot
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/docroot'
        DRUSH_OPTIONS_URI: 'https://redaa.lndo.site'
  node:
    type: node:16
tooling:
  npm:
    service: node
  yarn:
    service: node
  node:
    service: node
  gulp:
    service: node